---
swagger: "2.0"
info:
  version: "2026-06-01"
  title: "gir.tax"
host: "gir.tax"
schemes:
- "https"
paths:
  /:
    get:
      responses:
        "200":
          description: "200 response"
          headers:
            Strict-Transport-Security:
              type: "string"
            Content-Type:
              type: "string"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::830482727482:role/gir-tax-s3-read-access"
        uri: "arn:aws:apigateway:eu-central-1:s3:path/gir.tax/index.html"
        httpMethod: "GET"
        responses:
          default:
            statusCode: "200"
            contentHandling: "CONVERT_TO_BINARY"
            responseParameters:
              method.response.header.Strict-Transport-Security: "'max-age=63072000; includeSubDomains; preload'"
              method.response.header.Content-Type: "integration.response.header.Content-Type"
        passthroughBehavior: "when_no_match"
  /rules/:
    get:
      responses:
        "200":
          description: "200 response"
          headers:
            Strict-Transport-Security:
              type: "string"
            Content-Type:
              type: "string"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::830482727482:role/gir-tax-s3-read-access"
        uri: "arn:aws:apigateway:eu-central-1:s3:path/gir.tax/rules/index.html"
        httpMethod: "GET"
        responses:
          default:
            statusCode: "200"
            contentHandling: "CONVERT_TO_BINARY"
            responseParameters:
              method.response.header.Strict-Transport-Security: "'max-age=63072000; includeSubDomains; preload'"
              method.response.header.Content-Type: "integration.response.header.Content-Type"
        passthroughBehavior: "when_no_match"
  /{proxy+}:
    get:
      responses:
        "200":
          description: "200 response"
          headers:
            Strict-Transport-Security:
              type: "string"
            Content-Type:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Strict-Transport-Security:
              type: "string"
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::830482727482:role/gir-tax-s3-read-access"
        uri: "arn:aws:apigateway:eu-central-1:s3:path/gir.tax/{proxy}"
        httpMethod: "GET"
        responses:
          default:
            statusCode: "200"
            contentHandling: "CONVERT_TO_BINARY"
            responseParameters:
              method.response.header.Strict-Transport-Security: "'max-age=63072000; includeSubDomains; preload'"
              method.response.header.Content-Type: "integration.response.header.Content-Type"
          "404":
            statusCode: "404"
            responseParameters:
              method.response.header.Strict-Transport-Security: "'max-age=63072000; includeSubDomains; preload'"
        requestParameters:
          integration.request.path.proxy: "method.request.path.proxy"
        passthroughBehavior: "when_no_templates"
x-amazon-apigateway-security-policy: "TLS_1_0"
x-amazon-apigateway-binary-media-types:
- "*/*"
