#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path

import yaml


REPO_ROOT_DIR = Path(__file__).resolve().parents[1]
RULES_FILE = REPO_ROOT_DIR / "gir-validation" / "rules.yaml"
OUTPUT_FILE = REPO_ROOT_DIR / "app" / "girrules.js"


def main() -> None:
    with RULES_FILE.open("r", encoding="utf-8") as f:
        rules_data = yaml.safe_load(f)

    xmlnamespaces = rules_data["xmlnamespaces"]
    selected_rules = [rule for rule in rules_data["rules"] if "test" in rule]

    with OUTPUT_FILE.open("w", encoding="utf-8") as f:
        f.write("// This file is auto-generated by gir-validation/generatejs.py.\n")
        f.write("// Do not edit manually.\n\n")

        f.write("export const GIRNAMESPACES = ")
        f.write(json.dumps(xmlnamespaces, indent=2, ensure_ascii=False))
        f.write(";\n\n")

        f.write("export const GIRRULES = [\n")
        for rule in selected_rules:
            f.write("  {\n")
            f.write(f"    number: {rule['number']},\n")
            f.write(f"    targets: {json.dumps(rule['targets'], ensure_ascii=False)},\n")
            f.write(f"    test: {json.dumps(rule['test'], ensure_ascii=False)},\n")
            f.write(f"    rule: {json.dumps(rule['rule'], ensure_ascii=False)},\n")
            f.write(f"    description: {json.dumps(rule['description'], ensure_ascii=False)},\n")
            f.write("  },\n")
        f.write("];\n")

    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
