import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";

import { ASSERTION_OPS, ruleIsActive } from "../app/ruleeval.js";

const repoRootDir = ".";

const rulesFile = path.join(repoRootDir, "gir-rules", "rules.yaml");
const outputFile = path.join(repoRootDir, "app", "girrules.js");

// Runtime fields the app and the rule evaluator need. Authoring-only scaffolding
// (rule, element, references, implementation_notes,
// target_does_not_exist_in_test_files) is dropped — the operands are the source
// of truth once a rule is active.
const selectRuntimeRule = (rule) => {
  const operator = ASSERTION_OPS.find((op) => op in rule);
  const runtimeRule = {
    number: rule.number,
    targets: rule.targets,
  };
  if ("when" in rule) {
    runtimeRule.when = rule.when;
  }
  runtimeRule[operator] = rule[operator];
  runtimeRule.description = rule.description;
  return runtimeRule;
};

const indent = (text, spaces) => text
  .split("\n")
  .map((line) => `${" ".repeat(spaces)}${line}`)
  .join("\n");

const generateRulesModule = async () => {
  const rulesRaw = await readFile(rulesFile, "utf8");
  const rulesData = parse(rulesRaw);

  const xmlNamespaces = rulesData.xmlnamespaces;
  const activeRules = rulesData.rules.filter(ruleIsActive);

  let output = "";
  output += "// This file is auto-generated by scripts/generaterulesjs.js.\n";
  output += "// Do not edit manually.\n\n";

  output += "export const GIRNAMESPACES = ";
  output += `${JSON.stringify(xmlNamespaces, null, 2)};\n\n`;

  output += "export const GIRRULES = [\n";
  for (const rule of activeRules) {
    output += `${indent(JSON.stringify(selectRuntimeRule(rule), null, 2), 2)},\n`;
  }
  output += "];\n";

  await writeFile(outputFile, output, "utf8");
  console.log(`Wrote ${outputFile} (${activeRules.length} active rules)`);
};

generateRulesModule().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
