import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";

const repoRootDir = ".";

const rulesFile = path.join(repoRootDir, "gir-rules", "rules.yaml");
const outputFile = path.join(repoRootDir, "app", "girrules.js");

const generateRulesModule = async () => {
  const rulesRaw = await readFile(rulesFile, "utf8");
  const rulesData = parse(rulesRaw);

  const xmlNamespaces = rulesData.xmlnamespaces;
  const selectedRules = rulesData.rules.filter((rule) => Object.prototype.hasOwnProperty.call(rule, "test"));

  let output = "";
  output += "// This file is auto-generated by scripts/generaterulesjs.js.\n";
  output += "// Do not edit manually.\n\n";

  output += "export const GIRNAMESPACES = ";
  output += `${JSON.stringify(xmlNamespaces, null, 2)};\n\n`;

  output += "export const GIRRULES = [\n";
  for (const rule of selectedRules) {
    output += "  {\n";
    output += `    number: ${rule.number},\n`;
    output += `    targets: ${JSON.stringify(rule.targets)},\n`;
    output += `    test: ${JSON.stringify(rule.test)},\n`;
    output += `    rule: ${JSON.stringify(rule.rule)},\n`;
    output += `    description: ${JSON.stringify(rule.description)},\n`;
    output += "  },\n";
  }
  output += "];\n";

  await writeFile(outputFile, output, "utf8");
  console.log(`Wrote ${outputFile}`);
};

generateRulesModule().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
