name: Build and Deploy

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:

  rules-test:
    name: "Test Rules"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: python -m pip install -r gir-rules/requirements.txt
    - name: Test GIR Rules
      run: python gir-rules/test.py

  web-build:
    name: "Web Build"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Dependencies
      run: npm install
    - name: Check Licenses
      run: npm run license-check
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Run JavaScript Tests
      run: npm run test
    - name: Upload Distribution
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: dist
        path: dist

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs:
      - rules-test
      - web-build
    if: ${{ github.repository == 'marchof/gir.tax' && github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Download Distribution
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
      with:
        name: dist
        path: dist
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
      with:
        role-to-assume: arn:aws:iam::830482727482:role/github-workflow-gir.tax
        aws-region: eu-central-1
    - name: Deploy
      run: aws/deploy.sh
